name: Build Status

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "sqlite:///:memory:"  # 测试用数据库
      FLASK_APP: "psyas/app.py"          # 应用入口
      SECRET_KEY: "test-secret-key-for-github-actions"  # 测试用密钥（仅用于CI环境）

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Run Python lints
        run: flask lint --check
      - name: Run Python tests
        run: flask test
